### ISSUE TITLE
multi consumer queue seems to have sort of an ABA problem

### ISSUE THREAD

**Issue by anarazel** [frechilla/misc-playground#1]
As far as I can see the queues presented here aren't safe with multiple concurrent readers: The CAS can spuriously succeed if other threads have read/written enough to let the tail pointer wrap around to it's previous position.

I guess that problem can be either solved using a 'tagged tail pointer' or by adding a separate 'epoch' variable.

**Comment by frechilla** [comment]
It is true. I never found this problem using instances of this queue because they were too big for that to happen, or my computer too slow.

It is definitely worth revisiting the code and add a solution to this. Since it will add extra cycles (which under some circumstances are not really needed) it would be a good idea to be able to activate/deactivate it at compile time.

Thanks!

**Comment by frechilla** [comment]
Hi again,

I'm sorry it took this long but I was having a look at this again and I don't see how the issue you describe can happen.

 m_readIndex is an unsigned integer which keeps increasing. When it gets to 0xFFFFFFFF and it is increased again it wraps around to 0. This value is converted into an index that fits the size of the queue by making use of countToIndex.

> the queues presented here aren't safe with multiple concurrent readers: The CAS can spuriously succeed if other threads have read/written enough to let the tail pointer wrap around to it's previous position

If other threads have read/written enough to let the tail pointer wrap around to its previous position the CAS operation won't succeed, because it is based on the real value of m_readIndex (instead of the index converted to fit the size of the queue). 

For m_readIndex to wrap around and you would have to push/pop 4,294,967,296 elements. It is extremely unlikely that a thread is stuck while others can read/write 4 billion elements, but if that is still an issue the indexes can be converted into uint64_t, and unlikely turns into plain impossible.

**Comment by frechilla** [comment]
Closing this issue. I don't think there is an issue with multiple concurrent readers (See previous comment to learn why)
